version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.1.5-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: epadam/rasa-simple:latest
    expose: 5055
